version: "3.9"
services:
  api:
    build: ./
    image: rdallavalle/project2_api # api_image
    command: uvicorn --app-dir=./code main:api --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - api_network
  cicd:
    image: rdallavalle/project2_cicd # cicd_image
    environment:
      - LOG=1
    volumes:
      - logfiles:/home/api/logs
    depends_on:
      - api
networks:
  api_network:
    driver: bridge
volumes:
  logfiles:
